# Custom Language File for Launcher Customizer

[ejs.app]
title = "Utopia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Oracios/UtopiaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/QGcZWFQBgU"

[ejs.settings]
sourceGithubLink = "https://github.com/Oracios/UtopiaLauncher"
supportLink = "https://github.com/Oracios/UtopiaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Utopia 3.5"
welcomeDescription = """En rejoignant Utopia 3.5, vous reconnaissez et acceptez que votre pseudo, vos messages écrits, votre voix ainsi que vos actions en jeu puissent être enregistrés, diffusés et rediffusés par les créateurs de contenu participant au serveur, notamment sur des plateformes telles que Twitch, YouTube, TikTok ou tout autre réseau de diffusion.<br><br>Cette diffusion peut avoir lieu en direct ou sous forme de contenu publié ultérieurement (vidéos, clips, shorts, extraits, réseaux sociaux, etc.).<br><br>Si vous ne souhaitez pas apparaître dans des contenus enregistrés ou diffusés, nous vous invitons à ne pas rejoindre le serveur."""
welcomeDescCTA = "En cliquant sur Continuer, vous acceptez ces conditions."
